[package]
name = "dropper"
version = "0.1.0"
authors = ["Dropper Dev Team <dropper@pattyjog.al>"]

[dependencies]
scraper = "0.9.0"
curl = "0.4.19"
reqwest = "0.9.5"
regex = "1.1.0"
yaml-rust = "0.4.2"
